CONSUMER_KEY = 'put your twitter api key here'
CONSUMER_SECRET = 'put your twitter api secret here'
ACCESS_KEY = 'put your twitter access key here'
ACCESS_SECRET = 'put your twitter access secret here'
CLIENT_ID = 'put your reddit client id here'
CLIENT_SECRET = 'put your reddit client secret here'
API_KEY = 'put your bitly api key here'
